Fix json cannot be decoded when OPTIONS is called before POST
Calling a post with continue endpoint from a browser client I get the following error
exceptions.ValueError: No JSON object could be decoded

This fix is intended to ensure the endpoint if only fully executed when a POST method is called.